// check these routes!
const basicEmbed = require('../../../utilities/basicEmbed')
const errorEmbed = require('../../../utilities/errorEmbed')
const redditimage = require("@sujalgoel/reddit-image");
const {MessageEmbed} = require('discord.js')
module.exports = {
    name: 'meme',
    description: 'Gives you a meme', 
    usage(prefix){
        const returnArray = []

        //Basic usage shown in an array 

        // const single = `\`${prefix}${this.name.toLowerCase()}  @person %reason\``
        // const multiple = `\`${prefix}${this.name.toLowerCase()} @person1 @person2  %reason\` `
        // returnArray.push(single)
        // returnArray.push(multiple)
        return returnArray
    },
    requiredPermissions: [
            //All the required permissions the user and the bot both needs
    ], 
    isNSFW: false,
    minArgs: 0,
    maxArgs: 0,
    highValue: false, 
    emoji: null,
    uniqueText: "None",
    cooldown: 10,
    giflinks: [ 
        // Gif links for the embed
    ],
    async execute( message, args, text, client){
                
        const clientAsMember = message.guild.member(client.user.id)
            if(!message.channel.permissionsFor(clientAsMember).has('ATTACH_FILES')){
                return message.channel.send(basicEmbed(client,message, args, text, `Missing Permissions!`, `D:`, `I need permission to attach files in this channel!`))
            } 
            redditimage.fetch({ type: "meme" }).then(img => {
                message.delete()
                const newColor = Math.floor(Math.random()*16777215).toString(16)
                const embed = new MessageEmbed()   
                .setTitle(img[0].title)
                .setColor(newColor)
                .setDescription(`From ${img[0].author} at ${img[0].subreddit}(subreddit)
                                *Generated by the api [here](https://www.npmjs.com/package/@sujalgoel/reddit-image)*`)
                .setTimestamp()
                .setImage(img[0].image)
                .setFooter(`Asked for by ${message.author.username}`)
                message.channel.send(embed) 
            }) 
    }
}